### ISSUE TITLE
TcpProxy Unable to portforward some applications

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [CarlJamison/miseryjs#7]
```
Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at TcpProxy.TcpPortForwarder.TargetRead(IAsyncResult asyncResult) in C:\Users\kclark\source\repos\TcpProxy\TcpProxy\Program.cs:line 122
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

Tested using TcpProxy.cs and Remote Desktop (3389)

`$ node socket_server.js 3389`

and 

```
int targetPort = 3389, string targetHost = "192.168.1.20"
```
for the target server and ports on the `.cs` file.

Output on the `socket_server.js` file
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/57604669/211459948-7d4d362b-bd87-496b-bc49-09b22200468a.png">

**Comment by Invoke-Mimikatz** [comment]
Possibly an easier to troubleshoot error:

- Use `socket_server.js` with port 443 and `TcpProxy.cs` with host = "itgtrips.com" and port = "443"
- Browse on the local machine (the one running socket_server.js) to `https://127.0.0.1:443`
- Ignore security warnings for now (not important)
- Expected result: Connect to and see ITG Trips website
- Actual result: `socket_server.js` crashes with error:
```
/Users/kevin/tools/miseryjs/proxy_work/socket_server.js:25
    connections[msg.id].write(data);
                        ^

TypeError: Cannot read properties of null (reading 'write')
    at Socket.<anonymous> (/Users/kevin/tools/miseryjs/proxy_work/socket_server.js:25:25)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/Users/kevin/tools/miseryjs/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/kevin/tools/miseryjs/node_modules/socket.io/dist/socket.js:614:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by CarlJamison** [comment]
Need to see if this is still happening with recent changes

**Comment by CarlJamison** [comment]
fixeddddd
